[package]
name = "morrobroom"
version = "0.1.0"
edition = "2024"

[features]
default = ["serde"]
serde = []

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
delaunator = "1.1.0"
imagesize = "0.15.0"
mimalloc = "0.1.52"
nalgebra = "0.35.0"
nom = "8.0.0"
vfstool_lib = { version = "0.9.0", features = ["zip"] }
rayon = "1.12.0"
glam = "0.33.5"
lightmap = "0.7.0"
serde = { version = "1.0.229", features = ["derive"] }
usage = { version = "1.4.0", features = ["rayon"] }
openmw-config = "1.1.0"

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
branch = "main"
features = ["esp", "nif"]
