use std::collections::BTreeMap;

use rayon::iter::{IntoParallelRefIterator, ParallelIterator};
use usage::Usage;

use crate::slipgate::{
    EPSILON, FacePlanes, Plane3d, Vector3,
    brush::{BrushHulls, BrushId},
    face::FaceId,
};

pub enum FaceVerticesTag {}
pub enum FaceVertexPlanesTag {}

pub type FaceVertices = Usage<FaceVerticesTag, BTreeMap<FaceId, Vec<Vector3>>>;
pub type FaceVertexPlanes =
    Usage<FaceVertexPlanesTag, BTreeMap<FaceId, Vec<(FaceId, FaceId, FaceId)>>>;

pub fn face_vertices(
    brush_planes: &BTreeMap<BrushId, Vec<FaceId>>,
    face_planes: &FacePlanes,
    brush_hulls: &BrushHulls,
) -> (FaceVertices, FaceVertexPlanes) {
    brush_planes
        .par_iter()
        .flat_map_iter(|(brush_id, face_ids)| {
            let hull = &brush_hulls[brush_id];
            let planes = face_ids
                .iter()
                .map(|face_id| (*face_id, face_planes[face_id]))
                .collect::<Vec<_>>();

            let mut vertices = face_ids
                .iter()
                .map(|face_id| (*face_id, (Vec::new(), Vec::new())))
                .collect::<BTreeMap<_, _>>();

            // Each convex brush vertex is generated by one unique combination
            // of three of that brush's planes. Generate it once, then attach
            // the result to all three incident faces.
            for i in 0..planes.len() {
                for j in (i + 1)..planes.len() {
                    for k in (j + 1)..planes.len() {
                        let (p0_id, p0) = planes[i];
                        let (p1_id, p1) = planes[j];
                        let (p2_id, p2) = planes[k];

                        let Some(position) = triplanar_intersection(&p0, &p1, &p2)
                            .filter(|position| hull.contains(position))
                        else {
                            continue;
                        };

                        for (face_id, vertex_planes) in [
                            (p0_id, (p0_id, p1_id, p2_id)),
                            (p1_id, (p1_id, p0_id, p2_id)),
                            (p2_id, (p2_id, p0_id, p1_id)),
                        ] {
                            let (face_vertices, face_vertex_planes) = vertices
                                .get_mut(&face_id)
                                .expect("brush face must be indexed");
                            if face_vertices.iter().all(|existing| existing != &position) {
                                face_vertices.push(position);
                                face_vertex_planes.push(vertex_planes);
                            }
                        }
                    }
                }
            }

            vertices
                .into_iter()
                .map(|(face_id, (vertices, vertex_planes))| (face_id, vertices, vertex_planes))
        })
        .map(|(face_id, vertices, vertex_planes)| ((face_id, vertices), (face_id, vertex_planes)))
        .unzip()
}

pub fn triplanar_intersection(p0: &Plane3d, p1: &Plane3d, p2: &Plane3d) -> Option<Vector3> {
    let n0 = p0.normal();
    let n1 = p1.normal();
    let n2 = p2.normal();

    let denom = n0.cross(n1).dot(n2);

    if denom.abs() < EPSILON {
        return None;
    }

    Some(
        (n1.cross(n2) * p0.distance()
            + n2.cross(n0) * p1.distance()
            + n0.cross(n1) * p2.distance())
            / denom,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn triplanar_intersection_accepts_negative_orientation() {
        let x = Plane3d {
            n: Vector3::new(1.0, 0.0, 0.0),
            d: 1.0,
        };
        let y = Plane3d {
            n: Vector3::new(0.0, 1.0, 0.0),
            d: 1.0,
        };
        let z = Plane3d {
            n: Vector3::new(0.0, 0.0, 1.0),
            d: 1.0,
        };

        let vertex = triplanar_intersection(&x, &z, &y).expect("planes should intersect");

        assert_eq!(vertex, Vector3::new(1.0, 1.0, 1.0));
    }
}
