name: Morrobroom Manufacturing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ["*"]

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/rustGlobalBuild.yml@v42
    secrets: inherit
    with:
      # Required: JSON array of binary names to build. Add more for monorepos.
      binary_names: '["morrobroom"]'
      include_files: "README.md,LICENSE,THIRD_PARTY.md,resources,content"
      cargo_publish: false
      publish_docs: false
      enable_portmaster: false
      enable_android: false
